### Lunamatic configuration ###
# Choose which moon effects to enable
fullMoonEnabled: true
newMoonEnabled: true
## Ignored unless fullMoonEnabled == true
harvestMoonEnabled: true
## Ignored unless newMoonEnabled == true
bloodMoonEnabled: true
# Chance for Blood and Harvest Moons ###
# This sets the number of sides in the dice roll,
# e.g. 2 = coin-toss (50/50), 6 = normal die (17% chance)
bloodMoonDieSides: 2
harvestMoonDieSides: 2
# Set worlds to disable moon-effects on ###
# by design both nether & the_end cannot have moon effects
disabledWorlds:
  - world
  - world_nether
  - world_the_end
# Do you want to check for updates at server start?
checkForUpdates: true