# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload plugin JAR
      uses: actions/upload-artifact@v4
      with:
        name: plugin-jar
        path: build/libs/*all.jar
        retention-days: 4

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Clean the Server Plugins Cache
      run: ./gradlew cleanPaperPluginsCache

#    - name: Run PaperMC Server (1.21.1)
#      run: ./gradlew runServerTest -PmcVersion="1.21.1"
#    - name: Run PaperMC Server (1.21.4)
#      run: ./gradlew runServerTest -PmcVersion="1.21.4"
#    - name: Check the Server Logs
#      run: ./gradlew checkServerLogs

  test-paper:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download plugin JAR
        uses: actions/download-artifact@v4
        with:
          name: plugin-jar
          path: plugins

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run PaperMC Server in Docker with plugin
        run: |
            docker run -d \
            --name test-paper-server \
            -e EULA=TRUE \
            -e TYPE=PAPER \
            -e VERSION=1.21.1 \
            -v ${{ github.workspace }}/plugins:/plugins \
            -p 25565:25565 \
            itzg/minecraft-server
            
            echo "Waiting for server to start..."
            sleep 60
            
            echo "Fetching logs for sanity check:"
            docker logs test-paper-server

      - name: Stop and clean up
        if: always()
        run: docker rm -f test-paper-server