name: Purpur Server

on:
  workflow_run:
    workflows: ["Gradle Build"]  # Must match the name field of `build.yml`
    types:
      - completed

jobs:
  test-purpur:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download plugin JAR
        uses: actions/download-artifact@v4
        with:
          name: plugin-jar
          path: plugins

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run PaperMC Server in Docker with plugin
        run: |
          docker run -d \
          --name test-purpur-server \
          -e EULA=TRUE \
          -e TYPE=PURPUR \
          -e VERSION=1.21.1 \
          -v ${{ github.workspace }}/plugins:/plugins \
          -p 127.0.0.1:25565:25565 \
          itzg/minecraft-server:latest
          echo "Starting Purpur server..."
          sleep 2

      - name: Delayed server health check
        run: |
          echo "Waiting for server to become healthy..."
          for i in {1..20}; do
            healthy=$(docker exec test-purpur-server mc-monitor status --host 127.0.0.1 || echo "unhealthy")
            echo "Status: $healthy"
            if [[ "$healthy" == *"online"* ]]; then
              echo "Server is online!"
              docker exec -i test-purpur-server rcon-cli "luma cyclemoonstates"
              exit 0
            fi
            sleep 6
          done
          echo "Server failed health check, timeout."
          exit 1

      - name: Stop the server
        run: docker stop test-purpur-server || true

      - name: Retrieve server logs
        run: docker logs test-purpur-server

      - name: Check Minecraft server logs for errors
        run: |
          echo "Checking container logs for errors..."
          LOG_OUTPUT=$(docker logs test-purpur-server 2>&1)
          ERROR_LINES=$(echo "$LOG_OUTPUT" | grep 'ERROR]:' || true)
          if [ -n "$ERROR_LINES" ]; then
            echo "Errors were found in the server logs:"
            echo "$ERROR_LINES"
            exit 1
          else
            echo "No errors found in the container logs."
          fi

      - name: Stop and clean up
        if: always()
        run: docker rm -f test-purpur-server || true